### ISSUE TITLE
what happened? :(

### ISSUE THREAD

**Issue by Foggalong** [mirasmithy/epochlauncher#5]
Was excited about the 2.0 version but it's all gone now :(

**Comment by mirasmithy** [comment]
Hi Joshua! I pulled Epoch Launcher 2.0's code because of a memory bug. I should have the bug fixed and the code pushed within two days. At the moment, I looking to release Epoch Launcher 2.0 on Google Play and F-Droid in early-mid June.

**Comment by Foggalong** [comment]
Oh awesome! Thanks for the update :)

**Comment by mirasmithy** [comment]
No problem! I've pushed the code back to GitHub and should be pushing more code the next few days.
